### ISSUE TITLE
Update codecov addin runner to support official codecov binary

### ISSUE THREAD

**Issue by AdmiringWorm** [cake-contrib/Cake.Codecov#219]
The codecov team have deprecated the use of all community maintained applications, the community maintained applications will stop working in Januarry/February, as such this addin needs to be updated to ensure it is compatible with the official binary.

It is uncertain at this time if it will be a breaking change or not.

**Comment by gep13** [comment]
@AdmiringWorm what are your plans for sourcing the new official binary?

From what we can see, these can be found here:

https://uploader.codecov.io/

Should the Cake.Codecov addin source/download this binary depending on where it is being executed, or did you have a different plan for this?

Getting this out the door is obviously required before a new release of Cake.Recipe is made, since as of tomorrow, its support for Codecov will no longer work 😢

**Comment by gep13** [comment]
@AdmiringWorm I guess this makes sense.  Addins do tend not to actually download any files, so perhaps that becomes the responsibility of the parent Cake script, or external process to ensure that it is on disk, somewhere, that the addin can find it.

**Comment by nils-a** [comment]
As an example to the contrary, Cake.Gradle has a `BootstrapGradle()` alias that will download and provide the gradle wrapper 😄

**Comment by AdmiringWorm** [comment]
@nils-a or embed and extract the file as I do in Cake.Warp.

**Comment by gep13** [comment]
@AdmiringWorm I haven't checked, but does the license of the codecov uploader allow for redistribution?

**Comment by nils-a** [comment]
@AdmiringWorm, @gep13 I have created https://www.nuget.org/packages/CodecovUploader/ which bundles the official tool from Codecov in a NuGet. This way, the packages will be auto-updated, and we can keep the (IMHO good) separation of "tool" and "addin".

**Comment by AdmiringWorm** [comment]
@nils-a that is awesome, thank you for doing that.

It do look like however that your CI builds fail, and caused the package to be out of date

**Comment by gep13** [comment]
@AdmiringWorm @nils-a seems like the index URL has changed, no idea why, but the information your script requires can be found here (I think):

https://api.nuget.org/v3/registration5-semver1/codecovuploader/index.json

Rather than at:

https://api.nuget.org/v3-flatcontainer/CodecovUploader/index.json

**Comment by nils-a** [comment]
@AdmiringWorm Thanks for the heads-up. I kind of saw that, but didn't get around to fix it.

Thanks, @gep13, for figuring it out. 🙇‍♂️ 

The package has been updated and CI is running again. 🚀
