### ISSUE TITLE
Integrate the Codecov bash uploader

### ISSUE THREAD

**Issue by larzw** [cake-contrib/Cake.Codecov#3]
It may be useful to integrate the Codecov [bash uploader](https://github.com/codecov/codecov-bash) into the addin?

/cc @AdmiringWorm

**Comment by AdmiringWorm** [comment]
I'm not sure why it would be useful to integrate the bash uploader

**Comment by larzw** [comment]
I may not be worth it....One use case is, A user is running a build on Travis CI and needs to upload a javascript coverage report in there cake script? Maybe at that point we just have them call the bash uploader directly? Maybe the rare cases are not worth the extra complexity....thoughts? Thanks!

**Comment by AdmiringWorm** [comment]
It may be worth it in the long run, but I wouldn't see this as a priority right now.
IMO would be better to wait until the [codecov-exe](https://github.com/codecov/codecov-exe) have official support for linux/OS X instead of adding support of the bash uploader.

Or if there is an absolute need for supporting travis until linux support have been added to codecov-exe, then IMO it would be better to add support for [codecov-python](https://github.com/codecov/codecov-python) instead (although I've yet to find a way for it to work inside a cake build script though).

**Comment by larzw** [comment]
Thanks I like that plan.
