### ISSUE TITLE
Change build script to use Cake.Recipe

### ISSUE THREAD

**Issue by AdmiringWorm** [cake-contrib/Cake.Codecov#8]
Change the build and release process to make use of Cake.Recipe, instead of re-invent a new process.

**Comment by gep13** [comment]
@AdmiringWorm if you guys are willing to wait, then these tasks, and more, would be covered by switching to Cake.Recipe, rather than re-invent a new process.

**Comment by AdmiringWorm** [comment]
@gep13 I don't really mind.
Any ETA on when support for .NET Core will be stable enough on it?

**Comment by gep13** [comment]
@AdmiringWorm so, basic support is there today.  In the `setup.cake` file, you would call `Build.RunDotNetCore()` rather than `Build.Run()`.  This should then do the basics like:

- Run GitVersion
- Clean
- Restore
- Build

However, where it will start to break down is on the testing and publishing steps.  That is the part that still needs some work.  I have a presentation at the end of this week, so I will likely mainly be working on that this week, but aim to get this working before the end of the following week.

Would be interested in any help that you can offer.

**Comment by AdmiringWorm** [comment]
I see, well I'll have a look at it (remember I had problems setting up dotnet test on my Cake.Transifex addin).

I believe setting it up to work on appveyor is quite straight forward, but getting dotnet test to work correctly on linux and OSX (well on travis at least) is a pain, required quite a few hacks if I remember correctly when building with both .NET Core and .NET Full support (still haven't managed to build/test .NET Full correctly on OSX though).

**Comment by gep13** [comment]
@AdmiringWorm as a first pass, i had planned to take the work that you had done and put that into Cake.Recipe for unit testing.

**Comment by AdmiringWorm** [comment]
Well, feel free to use it.

I'm currently stuck on some issues with .NET Core, which makes me unable to restore/build and test .NET Core projects.
Needs to resolve that, before I can take a look at adding testing for .NET Core in Cake.Recipe.

**Comment by AdmiringWorm** [comment]
Migrating this repo to use Cake.Recipe or more or less done by now.
Only thing left before adding it as a default, is for the .NET Core side of Cake.Recipe is a little more stabilised (still haven't gotten around to test it on travis).
